# Generated by Django 3.1 on 2020-11-23 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agree',
            name='votes',
        ),
        migrations.RemoveField(
            model_name='informative',
            name='votes',
        ),
        migrations.RemoveField(
            model_name='like',
            name='votes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='question_text',
        ),
        migrations.RemoveField(
            model_name='replies',
            name='question_text',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='question_text',
        ),
    ]
